[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.0.0"
edition = "2024"

[workspace.dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
connie = { path = "crates/connie" }
crossbeam-channel = "0.5"
enumset = "1"
index_vec = "0.1"
itertools = "0.14"
line-index = "0.1"
logos = "0.15"
lsp-server = "0.7"
lsp-types = "0.97"
serde_json = "1"
wasm-encoder = "0.240"
wasmtime = "37"
wasmtime-wasi = "37"

[profile.release-with-debug]
inherits = "release"
debug = true
