name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - run: cargo run examples/hello.con

  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - vscode-platform: win32-x64
            rust-target: x86_64-pc-windows-gnu
            github-os: ubuntu-24.04
            ext: ".exe"
            install-script: sudo apt-get install -y mingw-w64
          - vscode-platform: linux-x64
            rust-target: x86_64-unknown-linux-musl
            github-os: ubuntu-24.04
            ext: ""
            install-script: ""
          - vscode-platform: darwin-x64
            rust-target: x86_64-apple-darwin
            github-os: macos-15-intel
            ext: ""
            install-script: ""
          - vscode-platform: darwin-arm64
            rust-target: aarch64-apple-darwin
            github-os: macos-15
            ext: ""
            install-script: ""
    runs-on: ${{ matrix.github-os }}
    steps:
      - uses: actions/checkout@v5
      - run: ${{ matrix.install-script }}
      - run: rustup target add ${{ matrix.rust-target }}
      - run: cargo build --release --target ${{ matrix.rust-target }}
      - uses: actions/upload-artifact@v4
        with:
          name: connie-${{ matrix.rust-target }}
          path: target/${{ matrix.rust-target }}/release/connie${{ matrix.ext }}
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: mkdir packages/connie-vscode/bin
      - run: cp target/${{ matrix.rust-target }}/release/connie${{ matrix.ext }} packages/connie-vscode/bin/connie${{ matrix.ext }}
      - run: bun run --filter=connie-vscode build -- --target ${{ matrix.vscode-platform }}
      - uses: actions/upload-artifact@v4
        with:
          name: connie-vscode-${{ matrix.vscode-platform }}
          path: packages/connie-vscode/connie-vscode-*.vsix
