name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: nixbuild/nix-quick-install-action@v34
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: actions/checkout@v5
      - run: nix flake check --print-build-logs

      - run: nix build --print-build-logs .#musl
      - uses: actions/upload-artifact@v5
        with:
          name: connie-x86_64-unknown-linux-musl
          path: result/bin/connie

      - run: nix build --print-build-logs .#windows
      - uses: actions/upload-artifact@v5
        with:
          name: connie-x86_64-pc-windows-gnu
          path: result/bin/connie.exe

      - run: nix build --print-build-logs .#vscode-linux-x64
      - uses: actions/upload-artifact@v5
        with:
          name: connie-vscode-linux-x64
          path: result/connie-vscode-*.vsix

      - run: nix build --print-build-logs .#vscode-win32-x64
      - uses: actions/upload-artifact@v5
        with:
          name: connie-vscode-win32-x64
          path: result/connie-vscode-*.vsix

  linux:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/download-artifact@v6
        with:
          name: connie-x86_64-unknown-linux-musl
      - run: chmod +x connie
      - run: ./connie --help

  windows:
    needs: build
    runs-on: windows-2025
    steps:
      - uses: actions/download-artifact@v6
        with:
          name: connie-x86_64-pc-windows-gnu
      - run: .\connie.exe --help
