name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  x86_64-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v5
      - run: nix flake check --print-build-logs

      - run: nix build --print-build-logs .#standalone
      - uses: actions/upload-artifact@v5
        with:
          name: moss-linux-x86
          path: result/bin/moss

      - run: nix build --print-build-logs .#windows
      - uses: actions/upload-artifact@v5
        with:
          name: moss-windows-x86
          path: result/bin/moss.exe

      - run: nix build --print-build-logs .#vsix-linux-x64 -o moss-linux-x64.vsix
      - uses: actions/upload-artifact@v5
        with:
          name: moss-vsix-linux-x64
          path: moss-linux-x64.vsix

      - run: nix build --print-build-logs .#vsix-win32-x64 -o moss-win32-x64.vsix
      - uses: actions/upload-artifact@v5
        with:
          name: moss-vsix-win32-x64
          path: moss-win32-x64.vsix

  linux-x86:
    needs: x86_64-linux
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/download-artifact@v6
        with:
          name: moss-linux-x86
      - run: chmod +x moss
      - run: ./moss --help

  windows-x86:
    needs: x86_64-linux
    runs-on: windows-2025
    steps:
      - uses: actions/download-artifact@v6
        with:
          name: moss-windows-x86
      - run: .\moss.exe --help
