name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  x86_64-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: nixbuild/nix-quick-install-action@v34
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: actions/checkout@v5
      - run: nix flake check --print-build-logs

      - run: nix build --print-build-logs .#standalone
      - uses: actions/upload-artifact@v5
        with:
          name: connie-linux-x86
          path: result/bin/connie

      - run: nix build --print-build-logs .#windows
      - uses: actions/upload-artifact@v5
        with:
          name: connie-windows-x86
          path: result/bin/connie.exe

      - run: nix build --print-build-logs .#vsix-linux-x64
      - uses: actions/upload-artifact@v5
        with:
          name: connie-vsix-linux-x64
          path: result

      - run: nix build --print-build-logs .#vsix-win32-x64
      - uses: actions/upload-artifact@v5
        with:
          name: connie-vsix-win32-x64
          path: result

  linux-x86:
    needs: x86_64-linux
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/download-artifact@v6
        with:
          name: connie-linux-x86
      - run: chmod +x connie
      - run: ./connie --help

  windows-x86:
    needs: x86_64-linux
    runs-on: windows-2025
    steps:
      - uses: actions/download-artifact@v6
        with:
          name: connie-windows-x86
      - run: .\connie.exe --help
